dataloader:
  dataset: 'iwslt2017'
  batch_size: 64
  num_workers: 4
  pin_memory: True
  drop_last: False
  shuffle: True
transformer:
  num_encoder_layers: 3
  num_decoder_layers: 3
  emb_size: 512
  dim_feedforward: 1024
  dropout: 0.1
trainer:
  learning_rate: 0.0001
  num_epochs: 200
  batch_size: 64
  tgt_batch_size: 512
  num_cycles: 6