dataloader:
  dataset: 'iwslt2017'
  batch_size: 64
  num_workers: 4
  pin_memory: True
  drop_last: False
  shuffle: True
transformer:
  num_encoder_layers: 4
  num_decoder_layers: 4
  emb_size: 512
  nhead: 8
  dim_feedforward: 2048
  dropout: 0.14
trainer:
  learning_rate: 0.0005
  num_epochs: 50
  tgt_batch_size: 1024
  warmup_steps: 3000