dataloader:
  dataset: 'multi30k'
  batch_size: 128
  num_workers: 4
  pin_memory: True
  drop_last: False
  shuffle: True
transformer:
  num_encoder_layers: 3
  num_decoder_layers: 3
  emb_size: 256
  nhead: 4
  dim_feedforward: 1024
  dropout: 0.14
trainer:
  learning_rate: 0.0005
  num_epochs: 45
  tgt_batch_size: 256
  warmup_steps: 1500