dataloader:
  dataset: 'multi30k'
  batch_size: 128
  num_workers: 4
  pin_memory: True
  drop_last: False
  shuffle: True
transformer:
  num_encoder_layers: 4
  num_decoder_layers: 4
  emb_size: 512
  nhead: 16
  dim_feedforward: 1024
  dropout: 0.4
trainer:
  learning_rate: 0.0001
  num_epochs: 25
  tgt_batch_size: 512
  warmup_steps: 300